<a href="https://massstreetuniversity.com/"><img src="https://tutorials.massstreetuniversity.com/images/logo.png" alt="School Logo"></a><br><br><br>
<a href="http://tutorials.massstreetuniversity.com/transact-sql/">Tutorial Home</a> | <a href="https://tutorials.massstreetuniversity.com/transact-sql/basic/joining-tables.html">Previous</a> | <a href="https://tutorials.massstreetuniversity.com/transact-sql/basic/subqueries.html">Next</a>

<h1>Lesson 15. Combining Queries</h1>

You can combine the results set of more than one query without joining the tables together. The result sets of the tables have to have the same number of columns. The final column output will be defined by the column names in the first SQL statement. In actual practice, it is good to alias table and column names that are different so you can keep track of where things are going and what things are.

You can perform this magic by using the SQL UNION clause.

There are two kinds of UNION clauses.

UNION – Removes duplicates from the final result set.

UNION ALL – Does not remove duplicate records from the final result set.

The use case for this is difficult to model in a sample database. Usually, this need arises from data being generated by more than one highly complex SQL statement. This statement may be joining data across servers. The bottom line is, whatever the user is after, it could not be generated with a single SQL statement.

<h1>Examples</h1>

<strong>Example Usage Of Union And Union All</strong>

In [ ]:
USE AdventureWorks2016

SELECT RevisionNumber
FROM Sales.SalesOrderHeader
UNION
SELECT SalesOrderID AS RevisionNumber
FROM Sales.SalesOrderHeader


SELECT RevisionNumber
FROM Sales.SalesOrderHeader
UNION ALL
SELECT SalesOrderID AS RevisionNumber
FROM Sales.SalesOrderHeader

Copyright © 2020, Mass Street Analytics, LLC. All Rights Reserved.